SABastionHost:
    Type: AWS::EC2::Instance
    Properties:
      DisableApiTermination: 'false'
      InstanceInitiatedShutdownBehavior: stop
      ImageId: ami-70edb016
      InstanceType: t2.micro
      KeyName: 'EC2KP'
      Monitoring: 'false'
      SecurityGroups: [!Ref 'SASGBastionHost']
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'true'
          DeleteOnTermination: 'true'
          Description: Primary network interface
          DeviceIndex: 0
          SubnetId: !Ref 'PublicSubnetA'
          GroupSet: [!Ref 'SASGapp']
      Tags:
        - Key: environment
          Value: Alscient-Aws-SA-Assignment
        - Key: Name
          Value: !Join ['-', [BastionHost, !Ref 'CandidateName']]

  SASGBastionHost:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SA Assignment - Bastion host Security Group
      VpcId: !Ref 'SAVPC'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: environment
          Value: Alscient-Aws-SA-Assignment
        - Key: Name
          Value: BastionHostSecurityGroup